# Generated by Django 4.1 on 2023-01-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField(choices=[('male', 'Male'), ('female', 'Female'), ('transegender', 'transegender')])),
                ('course', models.TextField(choices=[('web development', 'web development'), ('python', 'python'), ('c++', 'c++'), ('java', 'java'), ('mysql', 'mysql'), ('html', 'html')])),
                ('batch_time', models.TextField(choices=[('9 TO 12', '9 TO 12'), ('12 TO 2', '12 TO 2'), ('2 TO 5', '2 TO 5')])),
                ('phone_no', models.IntegerField()),
                ('email', models.TextField(max_length=30)),
            ],
        ),
    ]
