# Generated by Django 4.1 on 2023-01-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_course_alter_register_batch_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='batch_time',
            field=models.TextField(choices=[('9-12', '9-12'), ('1-2', '12-2'), ('2-5', '2-5')]),
        ),
    ]
