# Generated by Django 4.1 on 2023-01-14 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_attendences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendences',
            name='register_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.register'),
        ),
    ]
