# Generated by Django 4.1 on 2023-01-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_attendences_register_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendences',
            name='register_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_no',
            field=models.IntegerField(unique=True),
        ),
    ]
