# Generated by Django 4.1 on 2023-01-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_attendences_register_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_no', models.IntegerField()),
                ('exam_date', models.DateField()),
                ('mark_theory', models.IntegerField()),
                ('mark_pratical', models.IntegerField()),
            ],
        ),
    ]
