# Generated by Django 4.1 on 2023-01-19 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='batch_time',
            field=models.TextField(choices=[('9-12', '9-12'), ('12-2', '12-2'), ('2-5', '2-5')]),
        ),
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_no', models.IntegerField()),
                ('year', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.attendences')),
            ],
        ),
    ]
